# Generated by Django 5.2 on 2025-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(default='Admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
