# Generated by Django 5.2 on 2025-06-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_purchase_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
